
-- Kreiranje sekvenci za ID i trigera da poziva sekvencu kada se ID ne prosljedi

CREATE SEQUENCE NBP08.FACULTY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.FACULTY_TRIGGER
    BEFORE INSERT ON NBP08.FACULTY
    FOR EACH ROW
BEGIN

    IF :NEW.id IS NULL THEN
        SELECT NBP08.FACULTY_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.DEPARTMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.DEPARTMENT_TRIGGER
    BEFORE INSERT ON NBP08.DEPARTMENT
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.DEPARTMENT_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.CUSTOM_USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.CUSTOM_USER_TRIGGER
    BEFORE INSERT ON NBP08.CUSTOM_USER
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.CUSTOM_USER_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.LABORATORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.LABORATORY_TRIGGER
    BEFORE INSERT ON NBP08.LABORATORY
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.LABORATORY_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.CATEGORY_TRIGGER
    BEFORE INSERT ON NBP08.CATEGORY
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.CATEGORY_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.EQUIPMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.EQUIPMENT_TRIGGER
    BEFORE INSERT ON NBP08.EQUIPMENT
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.EQUIPMENT_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.SUPPLIER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.SUPPLIER_TRIGGER
    BEFORE INSERT ON NBP08.SUPPLIER
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.SUPPLIER_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.ORDERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.ORDERS_TRIGGER
    BEFORE INSERT ON NBP08.ORDERS
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.ORDERS_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.RENTAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.RENTAL_TRIGGER
    BEFORE INSERT ON NBP08.RENTAL
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.RENTAL_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;

CREATE SEQUENCE NBP08.SERVICE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER NBP08.SERVICE_TRIGGER
    BEFORE INSERT ON NBP08.SERVICE
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT NBP08.SERVICE_SEQ.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;